import os
import tempfile
import html
from typing import Dict, Optional

try:
    import weasyprint
    HAS_WEASYPRINT = True
except (ImportError, OSError):
    HAS_WEASYPRINT = False


def _build_html(
    tab_name: str,
    inputs_dict: Dict[str, str],
    results_dict: Dict[str, str],
) -> str:
    safe_tab_name = html.escape(str(tab_name))

    input_rows = "".join(
        f"<tr><td>{html.escape(str(k))}</td><td>{html.escape(str(v))}</td></tr>"
        for k, v in inputs_dict.items()
    )
    result_rows = "".join(
        f"<tr><td>{html.escape(str(k))}</td><td class='highlight'>{html.escape(str(v))}</td></tr>"
        for k, v in results_dict.items()
    )

    return f"""
    <html>
    <head>
        <meta charset="utf-8">
        <title>PSV Sizing Report - {safe_tab_name}</title>
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; color: #333; }}
            h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
            h2 {{ color: #2980b9; margin-top: 30px; }}
            table {{ border-collapse: collapse; width: 100%; margin-top: 15px; }}
            th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
            th {{ background-color: #f2f2f2; color: #333; width: 50%;}}
            .footer {{ margin-top: 50px; font-size: 12px; color: #7f8c8d; border-top: 1px solid #eee; padding-top: 10px; }}
            .highlight {{ color: #27ae60; font-weight: bold; }}
            @page {{ margin: 2cm; }}
        </style>
    </head>
    <body>
        <h1>Pressure Safety Valve (PSV) Sizing Report</h1>
        <p><strong>Calculation Scenario:</strong> {safe_tab_name}</p>
        <p><strong>Reference Standards:</strong> API Standard 520 (Part I) & API Standard 521</p>

        <h2>1. Input Parameters</h2>
        <table>
            <tr><th>Parameter</th><th>Value</th></tr>
            {input_rows}
        </table>

        <h2>2. Calculation Results</h2>
        <table>
            <tr><th>Result Parameter</th><th>Value</th></tr>
            {result_rows}
        </table>

        <div class="footer">
            Generated by PSV Sizing Suite v2.3.0 <br>
            Note: This report is for engineering review purposes. Always verify critical safety calculations.
        </div>
    </body>
    </html>
    """


def generate_report(
    tab_name: str,
    inputs_dict: Dict[str, str],
    results_dict: Dict[str, str],
    output_path: Optional[str] = None,
) -> str:
    """
    Generate a report for the PSV calculation.

    Returns the file path to the generated report.
    PDF if WeasyPrint is available, otherwise HTML.
    """
    html_content = _build_html(tab_name, inputs_dict, results_dict)

    if output_path is None:
        temp_dir = tempfile.gettempdir()
        ext = ".pdf" if HAS_WEASYPRINT else ".html"
        output_path = os.path.join(temp_dir, f"PSV_Sizing_Report{ext}")

    if HAS_WEASYPRINT:
        weasyprint.HTML(string=html_content).write_pdf(output_path)
    else:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html_content)

    return output_path


__all__ = ["generate_report", "HAS_WEASYPRINT"]