import os
import tempfile
from PyQt5.QtGui import QDesktopServices
from PyQt5.QtCore import QUrl

def generate_and_open_report(tab_name, inputs_dict, results_dict):
    html_content = f"""
    <html>
    <head>
        <title>PSV Sizing Report - {tab_name}</title>
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; color: #333; }}
            h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
            h2 {{ color: #2980b9; margin-top: 30px; }}
            table {{ border-collapse: collapse; width: 100%; margin-top: 15px; }}
            th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
            th {{ background-color: #f2f2f2; color: #333; width: 50%;}}
            .footer {{ margin-top: 50px; font-size: 12px; color: #7f8c8d; border-top: 1px solid #eee; padding-top: 10px; }}
            .highlight {{ color: #27ae60; font-weight: bold; }}
        </style>
    </head>
    <body>
        <h1>Pressure Safety Valve (PSV) Sizing Report</h1>
        <p><strong>Calculation Scenario:</strong> {tab_name}</p>
        <p><strong>Reference Standards:</strong> API Standard 520 (Part I) & API Standard 521</p>
        
        <h2>1. Input Parameters</h2>
        <table>
            <tr><th>Parameter</th><th>Value</th></tr>
            {"".join(f"<tr><td>{k}</td><td>{v}</td></tr>" for k, v in inputs_dict.items())}
        </table>
        
        <h2>2. Calculation Results</h2>
        <table>
            <tr><th>Result Parameter</th><th>Value</th></tr>
            {"".join(f"<tr><td>{k}</td><td class='highlight'>{v}</td></tr>" for k, v in results_dict.items())}
        </table>
        
        <div class="footer">
            Generated by PSV Sizing Suite v2.0 <br>
            Note: This report is for engineering review purposes. Always verify critical safety calculations.
        </div>
    </body>
    </html>
    """
    
    temp_dir = tempfile.gettempdir()
    report_path = os.path.join(temp_dir, "PSV_Sizing_Report.html")
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(html_content)
        
    QDesktopServices.openUrl(QUrl.fromLocalFile(report_path))
