import os
import html
import time
import tempfile
from PyQt5.QtGui import QDesktopServices
from PyQt5.QtCore import QUrl
from core import __version_tag__


def generate_and_open_report(tab_name, inputs_dict, results_dict, unit_system="USC"):
    safe_tab = html.escape(str(tab_name))
    unit_label = "USC (American)" if unit_system == "USC" else "SI (Metric)"
    safe_inputs = "".join(
        f"<tr><td>{html.escape(str(k))}</td><td>{html.escape(str(v))}</td></tr>"
        for k, v in inputs_dict.items()
    )
    safe_results = "".join(
        f"<tr><td>{html.escape(str(k))}</td><td class='highlight'>{html.escape(str(v))}</td></tr>"
        for k, v in results_dict.items()
    )
    html_content = f"""
    <html>
    <head>
        <title>PSV Sizing Report - {safe_tab}</title>
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; color: #333; }}
            h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
            h2 {{ color: #2980b9; margin-top: 30px; }}
            table {{ border-collapse: collapse; width: 100%; margin-top: 15px; }}
            th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
            th {{ background-color: #f2f2f2; color: #333; width: 50%;}}
            .footer {{ margin-top: 50px; font-size: 12px; color: #7f8c8d; border-top: 1px solid #eee; padding-top: 10px; }}
            .highlight {{ color: #27ae60; font-weight: bold; }}
        </style>
    </head>
    <body>
        <h1>Pressure Safety Valve (PSV) Sizing Report</h1>
        <p><strong>Calculation Scenario:</strong> {safe_tab}</p>
        <p><strong>Reference Standards:</strong> API Standard 520 (Part I), API Standard 521, API Standard 526</p>

        <h2>1. Input Parameters</h2>
        <table>
            <tr><th>Parameter</th><th>Value</th></tr>
            {safe_inputs}
        </table>

        <h2>2. Calculation Results</h2>
        <table>
            <tr><th>Result Parameter</th><th>Value</th></tr>
            {safe_results}
        </table>

        <h2>3. Standards &amp; Methods</h2>
        <table>
            <tr><th>Item</th><th>Reference</th></tr>
            <tr><td>Liquid relief sizing</td><td>API 520 Part I §5.8 (Q = 38·Kd·Kw·Kc·Kv·A·√(ΔP/G))</td></tr>
            <tr><td>Viscosity correction (Kv)</td><td>API 520 Part I Eq.34: Kv = (0.9935 + 2.878/Re^0.5 + 342.75/Re^1.5)^-1</td></tr>
            <tr><td>Gas/vapor sizing</td><td>API 520 Part I §5.6 (critical: C=520·√(k·(2/(k+1))^((k+1)/(k-1))))</td></tr>
            <tr><td>Two-phase (Omega method)</td><td>API 520 Part I Annex C (ηc, G, A = W/(25·G·Kd·Kb·Kc))</td></tr>
            <tr><td>Fire wetted relief load</td><td>API 521 §4.4.13 (Q = 21000·F·A^0.82)</td></tr>
            <tr><td>Fire unwetted area</td><td>API 521 (A' = F'·A/√P1)</td></tr>
            <tr><td>Thermal expansion load</td><td>API 521 §4.4.12 (Q = β·H/(500·G·Cp))</td></tr>
            <tr><td>Effective discharge coefficient (Kd)</td><td>API 520 Part I Table 1 (0.975 gas, 0.65 liquid)</td></tr>
            <tr><td>Orifice areas</td><td>API 526 (D = 0.110 ... T = 26.0 sq.in)</td></tr>
        </table>

        <div class="footer">
            Generated by PSV Sizing Suite {__version_tag__} <br>
            Unit System: {unit_label}<br>
            Note: This report is for engineering review purposes. Always verify critical safety calculations.
        </div>
    </body>
    </html>
    """
    
    temp_dir = tempfile.gettempdir()
    ts = int(time.time())
    report_path = os.path.join(temp_dir, f"PSV_Sizing_Report_{ts}.html")
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(html_content)
        
    QDesktopServices.openUrl(QUrl.fromLocalFile(report_path))
